Updating my caption
githubschool/verbose-octo-broccoli pull request #12
Opened 2022-02-03 21:10 UTC by Chocrates

Updating my slide's caption

2022-02-03 21:15 UTC, gitM-iru commented on _slides/02-Chocrates.md
> +Hello World!
Looks good

2022-02-03 21:20 UTC, gitM-iru reviewed
Please add comment.

2022-02-03 21:20 UTC, tommeenabong requested changes
Add hello to line 5

2022-02-03 21:22 UTC, tommeenabong approved these changes
awesome!

2022-02-03 21:23 UTC, merged

2022-02-03 21:23 UTC, SonLe20663 approved these changes

2022-02-04 20:09 UTC, Chocrates commented on _slides/02-Chocrates.md
>  ![femalecodertocat](https://octodex.github.com/images/femalecodertocat.png)
test